apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: ecommerce
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
    - job_name: 'istio-mesh'
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names: [ecommerce]
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
        action: keep
        regex: .*-metrics;.*-metrics
    - job_name: 'product-catalog'
      static_configs:
      - targets: ['product-catalog:8080']
    - job_name: 'order-service'
      static_configs:
      - targets: ['order-service:8080']
    - job_name: 'payment-service'
      static_configs:
      - targets: ['payment-service:8080']
    - job_name: 'user-service'
      static_configs:
      - targets: ['user-service:8080']