version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    container_name: miosa-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./users.acl:/data/users.acl
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - miosa-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: miosa-redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=admin
      - HTTP_PASSWORD=admin123
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - miosa-network

volumes:
  redis-data:
    driver: local

networks:
  miosa-network:
    driver: bridge