version: "3.9"
services:
  api:
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      - PORT=8080
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=chatapp
      - DB_PASSWORD=chatapp
      - DB_NAME=chatapp
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=supersecretjwtkey
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: chatapp
      POSTGRES_PASSWORD: chatapp
      POSTGRES_DB: chatapp
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
  web:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      - REACT_APP_API_URL=http://localhost:8080

volumes:
  db_data:
  redis_data: