package models

// Generated by Architecture Agent
// Task: Design data models and interfaces for: Create a real-time chat system with WebSocket support. Create Go structs.

import "time"

type Entity struct {
    ID        string    `json:"id"`
    Name      string    `json:"name"`
    CreatedAt time.Time `json:"created_at"`
    UpdatedAt time.Time `json:"updated_at"`
}