version: "3.9"
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./services/product-catalog/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./services/payment/schema.sql:/docker-entrypoint-initdb.d/02-schema.sql
  product-catalog:
    build: ./services/product-catalog
    ports:
      - "8081:8080"
    depends_on: [postgres]
    environment:
      DATABASE_URL: "postgres://postgres:postgres@postgres:5432/postgres"
  order-service:
    build: ./services/order
    ports:
      - "8082:8080"
    depends_on: [postgres]
    environment:
      DATABASE_URL: "postgresql+psycopg2://postgres:postgres@postgres:5432/postgres"
  payment-service:
    build: ./services/payment
    ports:
      - "8083:8080"
    depends_on: [postgres]
    environment:
      DATABASE_URL: "postgres://postgres:postgres@postgres:5432/postgres"
  user-service:
    build: ./services/user
    ports:
      - "8084:8080"
    depends_on: [postgres]
  api-gateway:
    build: ./services/api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - product-catalog
      - order-service
      - payment-service
      - user-service